### ISSUE TITLE
Trojan:Win32/Occamy.C In Current Build

### ISSUE THREAD

**Issue by dowen01** [GChristensen/enso-portable#14]
![trojan win32 occamy c](https://user-images.githubusercontent.com/2012453/45210013-608cc480-b286-11e8-9f00-8d367ae597d0.png)

Any ideas Guys?

**Comment by GChristensen** [comment]
https://github.com/GChristensen/enso-portable

>Known Issues
>Some AV tools may consider `run-enso.exe' as a potentially unwanted program. These are false-positive claims since the launcher uses API needed to run other programs.

https://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/
