### ISSUE TITLE
getDesktopOffset does not get Windows work area

### ISSUE THREAD

**Issue by robertcollier4** [GChristensen/enso-portable#15]
getDesktopOffset() is currently returned as (0,0) without checking Windows for the work area. This is a problem for users that have their taskbar at the top of the screen.
The following is a working code snippet which allows all the necessary calculations to be gotten.

    from ctypes import windll
    from ctypes import wintypes, byref
    SPI_GETWORKAREA = 48
    SystemParametersInfo = windll.user32.SystemParametersInfoA
    rectWorkarea = wintypes.RECT()
    SystemParametersInfo(SPI_GETWORKAREA, 0, byref(rectWorkarea), 0)
    workareaLeft = rectWorkarea.left
    workareaRight = rectWorkarea.right
    workareaTop = rectWorkarea.top
    workareaBottom = rectWorkarea.bottom
    workareaWidth = workareaRight - workareaLeft
    workareaHeight = workareaBottom - workareaTop

The suggested change affects the following files
https://github.com/GChristensen/enso-portable/blob/d0eb024cb2448673f5aafc51fe64e5d2d944d61a/enso/enso/platform/win32/graphics/__init__.py#L48
Currently getDesktopSize and getDesktopOffset are not being used anywhere in Win32 because they are calling the function with 0 arguments and getting a void return value. The functions in TransparentWindow.cxx write the information to the pointer addresses of the variables passed into them and return void. So neither getDesktopSize or getDesktopOffset are working as of now. The Win32 calls require passing in a pointer to an int structure as seen in:
https://github.com/GChristensen/enso-portable/blob/4fb927ca6c4ae4c66fa0fbbc33c088397f40b9ce/platform/win32/Graphics/TransparentWindow/TransparentWindow.cxx#L622
width also needs to be right minus left (in case of taskbar on left or right side).
height needs to be bottom minus top

Rather than dealing with dynamically allocated python variable pointers (which who knows what is going on with them) passed to the C code, best to do it all in python in enso/platform/win32/graphics/__init__.py with ctypes with the above code snippet.

**Comment by GChristensen** [comment]
BTW, I've fixed getDesktopSzie (it needs to be fixed, the pointers are packed to a Python list by a swig-generated c++ wrapper).

**Comment by GChristensen** [comment]
I think this is a too radical change from the default behavior and it should be optional (I think that Enso window was purposefully designed to appear at (0,0) coordinates). I'll add a custom initialization option to position Enso main window off the taskbar latter.
