### ISSUE TITLE
option to re-enable holding capslock?

### ISSUE THREAD

**Issue by ru-ni** [GChristensen/enso-portable#18]
This is the only version of enso I can get to work on w10 anymore. I like the new web interface thing, but I really wish you didn't just decide that nobody likes holding caps. 

I can't find settings for that in the web interface at all, nor mention of where I can go to change that.

Thanks for your work on this project

**Comment by gilch** [comment]
I also use the quasimode and was disappointed that the web UI didn't have the setting. Some love it some hate it. I think everyone should try it. The original Humanized version had it for good reasons and it just felt faster to release and go.

I did find the setting to turn it back on for mine. In `enso/config.py` change `IS_QUASIMODE_MODAL` to `False`.

A word of warning though. Disable the system shutdown and reboot commands if you don't like losing work. It's not likely to happen by accident if you have to hit enter, but it happened to me with release-and-go.

**Comment by ru-ni** [comment]
Thanks for the expeditious reply! I'm also surpsied that the config.py isn't tweakable via the webUI considering it has other config-y type things.

Thanks again and I hope you have a nice day, all

**Comment by GChristensen** [comment]
>I'm also surpsied that the config.py isn't tweakable via the webUI considering it has other config-y type things.

You can override any variable from config.py using custom initialization editor at the settings page.
