### ISSUE TITLE
Random freezes on anything

### ISSUE THREAD

**Issue by Hachiverol** [GChristensen/enso-portable#20]
In essence what I'm experiencing are freezes but on a ui level. For example I might try to type something like "open firefox", and it would totally freeze at "open fir" or any other point.
It happens with any command and the ui remains on the screen forever unless I right click on the taskbar icon and press restart. 
Is there any way to fix this or is it something isolated only to my specific setup? Worth noting I'm running Windows 10 LTSC.

**Comment by GChristensen** [comment]
Probably, some background process with admin privileges periodically hijacks input. It is very hard to debug in any case, and I probably can not help.

**Comment by Hachiverol** [comment]
> Probably, some background process with admin privileges periodically hijacks input. It is very hard to debug in any case, and I probably can not help.

Could it be my tablet driver? I don't have it connected at all time but the driver does run it the background. I don't know the nature of it though.
Discord is a possible culprit as well. I have some shortcuts set up for mic mute and deafen. I'll try without them and update
