### ISSUE TITLE
error after update windows 10

### ISSUE THREAD

**Issue by tnmeesters** [GChristensen/enso-portable#22]
Hello,

I get the following error, is there a solution for this?

File "C\Users\.....\AppData\Roaming\Enso\enso\platform\win32\shortcuts\Shortcuts.py", line 550, in _get_shortcuts
    shortcuts.append((shortcut_type, name.lower(), shortcut_path))
UnboundLocalError: local variable 'shortcut_path' referenced before assignment

Thank you.

**Comment by GChristensen** [comment]
Should be fixed in the new 0.5.1. Please, try this version.
