### ISSUE TITLE
add a license?

### ISSUE THREAD

**Issue by wolftune** [GChristensen/enso-portable#27]
This is missing a license. It seems to use various resources that might even *require* licensing (I found something referencing Mozilla Public License in the code when searching). Make sure whatever is chosen is compatible with any inherited licensing.

Anyway: https://choosealicense.com/

**Comment by GChristensen** [comment]
The original Enso is licensed under MIT. I'll add the original license file. MIT and MPL are compatible (it is possible to mix them).

**Comment by wolftune** [comment]
I don't care enough to be picky here or discuss that much, I just want to clarify: many compatible licenses are *one-way* compatible. So, MIT and MPL are indeed compatible as long as the combined mix is under MPL. The same for MIT and GPL.

Compatible does not mean MPL code can be included in an overall MIT project and keep the whole thing MIT. That said, all the MIT-licensed code can *stay* MIT. It's just that the use of the project as a whole must honor the terms of MPL unless someone is only using the MIT-licensed portion of the code.

**Comment by GChristensen** [comment]
Currently, the only MPL-licensed code in Enso Launcher is the markup of the settings pages. So it is definitely possible to use Enso without them. There is even an option to turn off the Web-based settings.

**Comment by wolftune** [comment]
I'm not a lawyer, and you'll almost surely have zero issues. So, last I'll say is that if it were me, I'd put the MPL stuff in a clearly segregated place or just make a statement about the presence of it in the README. I think you're fine though, and I'm not even complaining. Setting it as you have is fine with me.
