### ISSUE TITLE
Enso Launcher 1.1 closes immediately

### ISSUE THREAD

**Issue by UI-buff** [GChristensen/enso-portable#29]
Hi, I just installed enso-open-source-1.1-x86_64.exe on a new PC, running latest version of Windows 10 Pro - 22H2 build 19045.4170.
The installer seems to run well enough, but when I run Enso Open Source from the Start Menu, all I get is a "Closing Enso" popup right away.

Please advise? I'm happy to provide any log files etc. that might help, just not sure what.

(Side note: I'm no newbie to Enso - I've been using 0.6.1 for years on another PC and am happy with it)

Thanks in advance for looking into this, and for a great productivity tool!

**Comment by UI-buff** [comment]
Hi @GChristensen, and thanks for responding! 😄 

In fact, the culprit turned out to be an old .ensorc file in that same directory. Removed it, and Enso no longer insta-quits. Yay! 😃 🥳 
However, I did notice that the .ensorc file does not get auto-recreated - do I need to worry about that, or is that file no longer required?

**Comment by GChristensen** [comment]
It is currently undocumented old way of configuration. It is equivalent to the ensorc.py file in the .enso directory. It is recommended to use the latter one.

**Comment by UI-buff** [comment]
Great, thanks! 🙇 
Got another issue regarding adding commands pointing to control panel (.cpl) files.
Can I ask it here, or where do I go?

**Comment by GChristensen** [comment]
You may ask here. Enso uses `win32api.ShellExecute` from pywin32 to execute control panel applets (there are many already).
`rundll32.exe` is passed as the program and, for example, `shell32.dll,Control_RunDLL firewall.cpl` is passed as arguments to run the applet.
Unfortunately, technically I can't accept any donations now, but thanks anyway.

**Comment by UI-buff** [comment]
Odd, Patreon seemed to accept my payment. I've sent you a DM in there, hope we can clear the donation aspect up in that thread.

As for launching control panel windows through Enso, I'm baffled by the fact that I am able to simply find .e.g mmsys.cpl and do "Learn as open" and it works with version 0.6.1, whereas the latest version does not. Simply nothing happens when I try "open mmsys" after doing the learn as open.

I've seen the info about needing to sign Python to make elevated processes work, but for one thing, it seems very elaboratae, and secondly, I don't believe it applies to this issue, as, again, it works out of the box with Enso 0.6.1?

Thanks in advance for any help. 😄

**Comment by GChristensen** [comment]
Although there is probably a way. If you will use a command `learn as open your_applet`, there will be a shortcut .enso/commands/learned/mmsys.lnk. If you replace the "Target" path to `rundll32.exe shell32.dll,Control_RunDLL your_applet.cpl` , it should work and survive the Enso update. Enso restart is required after the shortcut was changed.

**Comment by UI-buff** [comment]
Wow, appreciate the detailed feedback! I'll give it a try.

May I also ask, is there a good reason why windows opened with Enso's Open command so often do not get focus? I guess it would be possible for me to add something to the Python code to ensure it did?

**Comment by UI-buff** [comment]
@GChristensen Any hope of this? (fixing the new-window-not-focused issue)?
If you could just point me to the specific file/script, that would be a big help - I'll try to tweak it myself.

**Comment by GChristensen** [comment]
Hi, I've somehow missed that message. I'll try to investigate.

**Comment by GChristensen** [comment]
I wasn't able to reproduce this so far. One thing to try is to replace [here](https://github.com/GChristensen/enso-portable/blob/61351f52f01367439e8810d2c482a9c9897545d8/enso/commands/open.py) SW_SHOWDEFAULT to SW_SHOWNORMAL or SW_SHOW. SW_SHOWDEFAULT tells the app to open window as the application wants it. Either the applications want their windows unfocused (for example there is already a running instance), or this may be somehow related to the settings of the Windows shell. Normally, it focuses the window.

**Comment by UI-buff** [comment]
Thanks for quick response!
I just tried a couple of times, and each time, first opening the Windows Calculator, then Notepad (both via Enso) leaves the focus on the Calculator. The Notepad never gets focus. This happens to me all the time with various apps, not just these two, to be clear.
I'm checking your link now. 😃

**Comment by UI-buff** [comment]
@GChristensen  And following up, I've now tried swapping all 3 occurrences of SW_SHOWDEFAULT in open.py with your suggestions (1 set at a time, with enso restart after each edit) - no joy. Except "Windows Calculator" was sudden listed twice as a completion choice after my first edit. Restoring the original open.py fixed that.

I'm at a loss here. But I reckon if I can work out to add what amounts to a "go <APPNAME>" command inside the script following every "open <APPNAME>", I'd be home free. It's what I often have to do manually right now.

It seems Notepad always opens unfocused for me if I use Enso, no matter what has focus at the time. Even on a blank desktop with no other windows. If I open it via the Start Menu, it has focus as expected. Weird.

**Comment by GChristensen** [comment]
I can only suggest to run it in a clean environment, such as [Windows Sandbox](https://learn.microsoft.com/en-us/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-overview), or a clean Windows installation. If it works there, this must be some software conflict.

**Comment by UI-buff** [comment]
@GChristensen  This is in fact a fresh Windows install on a new PC. But just to make sure, I just tried this test in a Windows Sandbox window - same result there. (Thanks for the tip, hadn't heard about this feature before)
Both when starting Notepad and Task Scheduler (both are Windows builtin apps), they do not get focus after using Enso's Open command - in my regular Windows 10 Pro or the Sandbox, it makes no difference.

I'm using the following version of Enso, and installing normally (not portable): enso-open-source-1.1-x86_64.exe

Am I cursed? It wouldn't be the first time... 😆 

> I can only suggest to run it in a clean environment, such as [Windows Sandbox](https://learn.microsoft.com/en-us/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-overview), or a clean Windows installation. If it works there, this must be some software conflict.

**Comment by UI-buff** [comment]
@GChristensen  And I can add to the above, the "Notepad not getting focus" does not occur when using Enso 0.6.1 on a different PC.

Could you perhaps either point me in the right direction to fixing it by adding the equivalent of an Enso "go" command to the "open" section somewhere in the code, or alternatively, perhaps there might be a bugfix you could do? Or perhaps I'm alone in having this issue?
