### ISSUE TITLE
Is there a way to display newlines? Or can you add one?

### ISSUE THREAD

**Issue by gilch** [GChristensen/enso-portable#33]
There are some cases when I display messages when I would like to show multiple lines of text. They seem to be replaced with spaces. I can work around this by replacing newlines with some other separator string, like `" | "`, but it's not as legible.

**Comment by GChristensen** [comment]
Messages require xml markup. Try to wrap them in <p>.

**Comment by gilch** [comment]
It still doesn't work. I tried `<p>`. I tried `<p>`line`</p>`. I tried `</p><p>`line`</p>`. I tried `caption=`. I looked at the `strings.py`, and it looks like there is a `<caption>` tag. `ensoapi.display_message()` must be adding tags and escaping mine.

**Comment by gilch** [comment]
Do you have a simple working example of `ensoapi.display_message()` outputting lines? I could probably figure it out from that. Or does Enso have some alternative to `display_message()` that I could use instead?

**Comment by GChristensen** [comment]
Yes, there is an alternative. The example is [here](https://github.com/GChristensen/enso-portable/blob/61351f52f01367439e8810d2c482a9c9897545d8/enso/scripts/run_enso.py#L40).

**Comment by GChristensen** [comment]
display_message indeed escapes the string.

The alternative requires such import: 
from enso.messages import displayMessage

**Comment by GChristensen** [comment]
This is fixed in v1.1.1. It is possible to set the UI font family through the UI_FONT variable in config.py or in the initialization block at the settings page. For example:
`
UI_FONT="Segoe UI"`
