### ISSUE TITLE
Simultaneous messages overlap illegibly

### ISSUE THREAD

**Issue by gilch** [GChristensen/enso-portable#34]
If Enso needs to display another message before the last one has been dismissed, they overlap and can't be read. The next message should display in a different location, or the previous one should be shifted vertically (preferably) or even horizontally to make room for it. This seems unavoidable if an exception escapes after a message has been shown, but at least I have the `traceback` command in that case.

As a workaround, I'm currently concatenating my messages for a single command, but as I can't print newlines #33, it's hard to separate them.

**Comment by GChristensen** [comment]
Enso has a simple modal messaging system. This means that a user interaction is required to dismiss a message. It is not designed for complex workflows. Some other tools such as tcl/tk or pyQt should be used for complex UIs.

**Comment by GChristensen** [comment]
You need to wrap lines in &lt;p&gt;. To display them separately. See the example at enso/strings.py
