### ISSUE TITLE
Missing simplejson module

### ISSUE THREAD

**Issue by thdoan** [GChristensen/enso-portable#4]
One thing I wanted to point out is that in your portable binary (enso-portable.7z.sfx.exe), the simplejson module is missing, so the `website` command didn't work out of the box. To fix that, I unzipped the simplejson directory inside simplejson‑3.6.5.win32‑py2.5.exe from http://www.lfd.uci.edu/~gohlke/pythonlibs/ and placed it in python/Lib/site-packages.

**Comment by GChristensen** [comment]
fixed
