### ISSUE TITLE
Symbols input not working in Windows 8.1 64-bit

### ISSUE THREAD

**Issue by thdoan** [GChristensen/enso-portable#6]
I'm not sure whether the issue is with Windows 8.1 or the 64-bit platform, but in any case it's fixed (and more efficient because I got rid of the unnecessary "somekey" event handler). You can grab the fix from here:

https://github.com/thdoan/enso-portable/commit/2dd6db78f40811d78fe9a162ec95eac14bda2250

**Comment by GChristensen** [comment]
Hi, I've tested your code on Windows 8.1 x64 and it worked, although I applied your fix.
