### ISSUE TITLE
Open command priority / history

### ISSUE THREAD

**Issue by mawiseman** [GChristensen/enso-portable#8]
Hey

I used to use enso way back when and it's great to see it still going!

I thought it used to prioritize your open results by most used then alphabetically?
It's a pain to keep tapping down 10 times to open notepad++

**Comment by GChristensen** [comment]
Hi, it seems that Enso uses 'string nearness' to give out suggestions. It is computed at enso/utils/strings.py
If you want to type less try: 'o TAB ++ ENTER', or use Emacs instead :)
