### ISSUE TITLE
How to build a release package?

### ISSUE THREAD

**Issue by kenny-evitt** [GChristensen/enso-portable#9]
It seems like the steps are:

 1. Compile the Python source files by running `python -m compileall .` in the *enso* sub-directory.
 2. Build the 'launcher' executable in Visual Studio (or using MSBuild).
 3. Copy the launcher executable to the *enso* sub-directory.
 4. Copy the embedded Python files to the *enso* sub-directory.
 5. Create archive (e.g. ZIP) files from the *enso* sub-directory.

Where are you getting the Python files? Can you add them to this repo, perhaps in a top-level *python* directory?

Am I missing anything else?

**Comment by GChristensen** [comment]
Hi,

If you just need a binary distrib, you can download it in the release
seciton: https://github.com/GChristensen/enso-portable/releases (the
version that is based on Python 2.5 is v1.5)
If you making a mod, you can use any portable python 2.7/2.5 with the
corresponding version, or take it from the releases above.

**Comment by kenny-evitt** [comment]
@GChristensen Thanks for the quick reply! I was mostly curious that, if I were to make any modifications, I could 'deploy' them to myself or on other computers.

But besides the Python interpreter and the launcher program, all of the other code seems to be in Python, so it should be easy enough to run a 'dev' version – right?

**Comment by GChristensen** [comment]
There is a couple of I/O libraries written in C++ (the complete original
community Enso source is available here:
https://bazaar.launchpad.net/%7Ecommunityenso/enso/community-enso/tarball/145?start_revid=145
), but yes, everything other is written in python. You can make direct
changes in a distribution.
